### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by LZakaria** [OvRcode/ovrride#140]
I just got sideswiped with an idea!!!

How about instead of worrying about having a gallery hosted on our site or worrying about what kind of gallery to implement... why don't we have a link that directly goes to our Instagram??

Like if you go to this site: http://durdenbarnyc.com/
and click on "gallery" in the menu it takes you directly to their insta page... 

Anyway, that seems kinda simple and easy to implement. Can we do this???

**Comment by barnardm** [comment]
scrapping this for now, design overhaul probably going to happen soon
