### ISSUE TITLE
Photo Gallery Plugin

### ISSUE THREAD

**Issue by jscottmorse** [OvRcode/ovrride#155]
Hello 

I know you are all really busy....

Is there any way we can install the Easing Slider "Lite" plugin to WordPress? It seems like a small simple plugin that allows us to create photo gallery sliders, which would really be awesome for blog content. 

Please let me know.

**Comment by barnardm** [comment]
we now have meta slider installed if we need slider/carrousel type photo displays and they can be embedded in any post via a shortcode
