### ISSUE TITLE
Skip to toolbar when tabbing forms

### ISSUE THREAD

**Issue by AJ-Acevedo** [OvRcode/ovrride#169]
After updating to WP 3.9.1 and all of the plugins in development i receve a "Skip to toolbar" popup message in Chrome when tabbing from the First to the Last Name fields on the following page. http://localhost/shop/rb07-05-14/

When inspecting the popup element I see the following

``` html
<a class="screen-reader-shortcut" href="#wp-toolbar" tabindex="1">Skip to toolbar</a>
```

**Comment by barnardm** [comment]
this doesn't seem to be happening any more, not sure if it was a wordpress/woocommerce update that resolved it or redesigning the product forms when we switched to a custom product plugin
