### ISSUE TITLE
CRITICAL: Mobile Rendering

### ISSUE THREAD

**Issue by huebschie** [OvRcode/ovrride#231]
See #devops Slack channel.

**Comment by barnardm** [comment]
I'm pretty sure this was an issue with memcached running out of memory and flushing part of the page cache which left only a garbled fragment of a page to display from cache. I initially tried moving from memached running on the HHVM servers to a dedicated memcached server, which worked for a while but seemed to have failed under early season load. I've now switched the page cached to a dedicated Redis server which should be able to handle the page cache more gracefully. If we don't see this pop up again by christmas I'm confident that it's fixed.

**Comment by barnardm** [comment]
Happened again today, Looks like w3total cache dropped the connection to redis. I restarted the server and flushed the cache and it seemed to straighten out

**Comment by barnardm** [comment]
At this point I'm thinking it's possibly some kind of issue with cloudflare and I'm working to get that switched out. Currently waiting on our domains to transfer to a new registrar so i can make DNS changes soon.

**Comment by barnardm** [comment]
Turns out it wasn’t cloud flare or any of our caching but it was HHVM. Turns out they’re going to be moving away from PHP compatibility anyway so I rebuilt the web servers with PHP 7.2 FPM this week.
