### ISSUE TITLE
Backend Editing Failure

### ISSUE THREAD

**Issue by huebschie** [OvRcode/ovrride#235]
Not sure this is the right place - but a bit out of my capability to solve...hit this error while trying to create a post:
load-scripts.php:477 Uncaught SyntaxError: Invalid or unexpected token

Not sure if this is a core Wordpress issue - or an exception created by working on a wifi network.

The end result of this failure is I'm unable to do any of the following while editing a specific post (post=74388):
- Edit the tags
- Add additional media
- View the text editor (HTML Code)

I need this page for an adwords campaign landing.....

**Comment by NerdyDillinger** [comment]
Tried clearing your browser cache? https://stackoverflow.com/a/47045076

**Comment by huebschie** [comment]
@NerdyDillinger worked like a charm! I had to dump my lifetime cache and cookies as well. (Probably helped overall performance anyway!) THANKS!
