### ISSUE TITLE
Remove vagrant/chef setup

### ISSUE THREAD

**Issue by barnardm** [OvRcode/ovrride#237]
Old dev environment that used vagrant and chef. Going forward the docker setup in the OvRcode/devTools repo will be the best way to run the dev environment locally. The following files/folder need to be removed:
- [x] dev.sql
- [x]  Vagrantfile
- [x] Vagrantfile.chef
- [x] Gemfile
- [x] Cheffile
- [x] Cheffile.lock
- [x] .ruby-gemset
- [x] .ruby-version
- [x] site-cookbooks/
- [x] roles/
- [x] nodes/
- [x] environments/
- [x] data_bags/
- [x] cookbooks/
- [x] chef/
- [x] .chef/

**Comment by AJ-Acevedo** [comment]
Is there documentation available for setting up the dev environment in docker?

**Comment by barnardm** [comment]
I think there’s some in the dev tools repo but it’s definitely on the light side. I need to make some tweaks to that repo anyways so I’ll get that updated.
