### ISSUE TITLE
Calendar/Kindbar Ad not loading properly

### ISSUE THREAD

**Issue by barnardm** [OvRcode/ovrride#240]
Every other time or so the homepage is loading approximately 1/4 of the kind bar spot loads and the calendar doesn't show up. No errors showing in console. Observed issue in production and development environment.

Originally thought a bad image file name in the slider was causing the issue but changing the file name hasn't resolved the issue.

**Comment by huebschie** [comment]
Load time error? I've noticed quite a few - as our homepage takes some time
to load....

**Comment by barnardm** [comment]
I think this was being caused by a Javascript function that was firing at document ready to adjust the size of an element, turns out we didn't need that function and I pulled it. I'm going to keep an eye out but I think this was solved with 900ff06aa88582b132291c5e4580ed900a1ad215

**Comment by barnardm** [comment]
Haven’t seen this pop in the last two days, calling this one resolved
