### ISSUE TITLE
Design of site in Mobile 

### ISSUE THREAD

**Issue by jeksulu** [OvRcode/ovrride#26]
@nedlymandico Can we make the design change so that it reads in this format when it goes down to the mobile size?
- [ ] 1. Header
- [ ] 2. Nav Bar
- [ ] 3. Feature slider 
- [ ] 4. 2 next Blog articles 
- [ ] 5. Calendar 
- [ ] 6. Upcoming trips 
- [ ] 7. Twitter Feed 
- [ ] 8. Instagram 
- [ ] 9. Newsletter Signup 
- [ ] 10. Footer 

All other things should disappear, such as:
- [ ] 1. Desintations 
- [ ] 2. Roddy Piper 
- [ ] 3. Google Map 
- [ ] 4. About 
- [ ] 5. FB Plug in

All Make Sense?  Easily implementable?

**Comment by barnardm** [comment]
closing this, relates to old setup
