### ISSUE TITLE
Set preferred image when posting a links to ovrride.com from Facebook

### ISSUE THREAD

**Issue by AJ-Acevedo** [OvRcode/ovrride#29]
When a facebook user posts a link to override.com on facebook, it does not display an OvR image.

See example:
![screen shot 2013-09-09 at 8 55 22 pm](https://f.cloud.github.com/assets/953092/1125352/dde03aa2-1b0f-11e3-8e64-055a5bf54c95.png)

Facebook uses these meta tags they look for in the <head> of the site ,
called open graph tags, so I uploaded a sized OVR logo and inserted

<link rel="image_src"
href="http://ovrride.com/wp-content/uploads/2012/01/ovr_fb.jpg">

at the bottom of the head, and that tells facebook to use that image
as its Like thumbnail...

Here's a little background:
[Facebook Open Graph](http://developers.facebook.com/docs/opengraph/)

[Here is a reference on how to fix it](http://www.hyperarts.com/blog/how-to-control-facebook-image-thumbnail-text-popup-dialogs/)

Here's how we fixed it last time by placing this at the bottom of the `<head>`:

``` html
<link rel="image_src" href="http://ovrride.com/wp-content/uploads/2012/01/ovr_fb.jpg">
```

**Comment by barnardm** [comment]
Just pushed updates yesterday to fix this. Image will pull either the featured image for posts or the ovr logo for the home page and products. Description pulls from the post excerpt or the description for products.
