### ISSUE TITLE
Setup Twitter Open Graph

### ISSUE THREAD

**Issue by AJ-Acevedo** [OvRcode/ovrride#39]
Add the Twitter Cards, Open Graph meta tags the same way we have it setup for facebook.

Reference: http://www.quicksprout.com/2013/03/25/social-media-meta-tags-how-to-use-open-graph-and-cards/

https://dev.twitter.com/docs/cards

**Comment by barnardm** [comment]
this is possibly fixed with the facebook issue being resolved, need to find a tool to verify we're good on twitter.
