### ISSUE TITLE
Gift Cert Glitch!

### ISSUE THREAD

**Issue by LZakaria** [OvRcode/ovrride#91]
Hey Guys.. I need your help. I created the products/coupons for the gift cert program. When I originally created the choose your own amount GC I tested it and it worked perfectly last week... and now it's not working. I've looked at it, I've tried to recreate it and I have NO clue why all of a sudden it doesn't work. When you go to add it to cart... the screen says "cart is empty".

Any chance someone can take a look at it and figure it out???

Here's the directions on creating a GC/coupon .... http://docs.woothemes.com/document/smart-coupons/

**Comment by barnardm** [comment]
Closing this issue, just tested on current plugin versions and the upstream bug seems to be closed.
